config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events
  resources :users, only: [:show]
  resources :event_attendances, only: [:create, :destroy]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  # direct link to event_attendance model
  has_many :event_attendances, foreign_key: :attended_event_id
  
  # Gets to users model through event_attendance model because event_attendance's event_attendee_id column is linked to user model
  has_many :attendees, through: :event_attendances, source: :event_attendee
  
  belongs_to :creator, class_name: "User"

  # Create class methods to separate Events by upcoming and past
  # def self.upcoming
  #   @upcoming = Event.where(date: (Time.now)..).order(:date)
  # end
  # def self.past
  #   @past = Event.where(date: ..(Time.now)).order(date: :desc)
  # end

  # Refactored class methods into scopes
  scope :upcoming, -> { where(date: (Time.now)..) }
  scope :past, -> { where(date: ..(Time.now)) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/signup.rb
class Signup < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # direct link to event_attendance model
  has_many :event_attendances, foreign_key: :event_attendee_id

  # link for attendees to event model through event_attendance model. dont need "source:" because event_attendance has column named "attended_event_id" 
  has_many :attended_events, through: :event_attendances
  
  # direct link to event model for creators
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user!
  def create
    @attendance = current_user.event_attendances.build(event_attendance_params)
    
    if @attendance.save
      flash.notice = "See you there!"
      redirect_back_or_to(Event.find(@attendance.attended_event_id))
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @attendance = EventAttendance.find_by(event_attendee_id: current_user.id, attended_event_id: params[:id])
    @attendance.destroy

    redirect_to event_path, alert: "You are no longer attending the event."
  end
  

  private

  def event_attendance_params
    params.require(:event_attendance).permit(:event_attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def show
    @attendance = EventAttendance.new
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:notice] = "Event created!"
      redirect_to @event
    else
      render :new, :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:location, :date)
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_account.html.erb
<% if user_signed_in? %>
  <div>Currently Signed in as: <%= link_to current_user.email, user_path(current_user) %></div>
  <div>    
    <%= link_to "Create New Event", new_event_path %> | 
    <%= link_to "Sign Out", destroy_user_session_url %>
  </div>
<% else %>
  <div> <%= link_to "Sign In", new_user_session_path %> | 
  <%= link_to "Sign Up", new_user_registration_path %></div>
<% end %>

app/views/events/_attend.html.erb
<%= form_with model: @attendance do |form| %>
  <%= form.hidden_field :attended_event_id, :value => @event.id %>
  <%= form.hidden_field :event_attendee_id, :value => current_user.id %>
  <%= form.submit 'Attend Event' %>
<% end %>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <h2>
    <%= link_to event.location, event %>
  </h2>

  <p>
    <strong>Event Organizer:</strong>
    <%= link_to event.creator.email, event.creator %>
  </p>
  <p>
    <strong>Date:</strong>
    <%= event.date.strftime("%m/%d/%Y") %>
  </p>
</div>

app/views/events/_unattend.html.erb
<%= button_to 'Unattend Event', event_attendance_path, method: :delete %>

app/views/events/index.html.erb
<%= render 'account' %>

<h1>Upcoming Events:</h1>
<div>
  <% @events.upcoming.order(:date).each do |event| %>
    <%= render event %>
  <% end %>
</div>

<h1>Past Events:</h1>
<div>
  <% @events.past.order(date: :desc).each do |event| %>
    <%= render event %>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :location, "Location:" %>
    <%= form.text_field :location %> 
  </div>
  <div> 
    <%= form.label :date, "Date:" %>
    <%= form.date_select :date %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<%= render 'account' %><br>

<div><%= link_to "View All Events", events_path %></div><br>

<div id="events">
  <div>
    <h1>
      Event Location: <%= @event.location %>
    </h1>
    <p>
      <strong>Event Organizer:</strong>
      <%= @event.creator.email %>
    </p>
    <p>
      <strong>Date:</strong>
      <%= @event.date.strftime("%m/%d/%Y") %>
    </p>
  </div>

  <% if user_signed_in? %>
    <% if current_user.attended_events.include?(@event) %>
      <div><%= render 'unattend' %></div>
    <% else %>
      <div><%= render 'attend' %></div>
    <% end %>
  <% else %>
    <p><%= button_to 'Login', new_user_session_path %> to let us know you're attending.</p>
  <% end %>
</div>

<h2>Guest List</h2>
<% if @event.attendees.any? %>
  <div><%= pluralize(@event.attendees.count, "attendee") %>:</div>
  <ul>
    <% @event.attendees.order(:email).each do |attendee| %>
      <li><%= attendee.email %></li>
    <% end %>
  </ul>
<% else %>
  <p> This event currently has no one registered to attend. </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice" style="color: green"><%= notice %></p>
    <p class="alert" style="color: red"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= render 'events/account' %>
<br>
<h1><%= @user.email %>'s Profile</h1>
<h2>Created Events:</h2>

<% @user.created_events.each do |event| %>
  <%= render event %> <br>
<% end %>
<br>
<h2>Event Attendance</h2>
<h3>Upcoming Events to Attend:</h3>
<ul>
  <% @user.attended_events.where(date: (Time.now)..).order(:date).each do |event| %>
      <li><%= event.location %> | Date: <%= event.date.strftime("%m/%d/%Y")%></li>
  <% end %>
</ul>
<br>
<h3>Past Events Attended:</h3>
<ul>
  <% @user.attended_events.where(date: ..(Time.now)).order(:date).each do |event| %>
      <li><%= event.location %> | Date: <%= event.date.strftime("%m/%d/%Y")%></li>
  <% end %>
</ul>